name: Generate Hash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate_hash:
    name: Generate Hash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SHA256 Hash
        run: |
          find ./test/src/main -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum > codebase.sha256
          echo "Hash generado correctamente:"
          cat codebase.sha256

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: codebase-sha256
          path: codebase.sha256      
